...

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -7,18 +7,91 @@
 #  https://github.com.cnpmjs.org/jgm/pandoc/releases/download/2.17.0.1/pandoc-2.17.0.1-macOS.zip
 #  TODO: provide gitcode
 
-___x_cmd_pandoc(){
-    while [ $# -gt 0 ]; do
-        case "$1" in
-            htt*)       x curl "$1"     ;;
-            # TODO: add resource for x path
-            *)          cat "$1"        ;;
-            # If json, use json color
-            # If source file, use language parser
-        esac
 
-        shift
-    done
+# if [ -z "$___X_CMD_PANDOC_BIN" ]; then
+#     if ! ___X_CMD_PANDOC_BIN="$(command -v pandoc 2>/dev/null)"; then
+
+#     fi
+# fi
+
+# x first
+# system second
+
+___x_cmd_pandoc_bin_default(){
+    printf "%s" "$___X_CMD_ROOT/.bin/pandoc"
+}
+
+___x_cmd_pandoc_bin_download_url_path(){
+    local sys="$(os rname)-$(os-arch)"
+    case "$sys" in
+        Darwin-*)
+            printf "%s" "2.17.0.1/pandoc-2.17.0.1-macOS.zip"
+            ;;
+        win-*)
+            printf "%s" "2.17.0.1/pandoc-2.17.1.1-windows-x86_64.zip"
+            ;;
+        linux-amd64)
+            printf "%s" "2.17.0.1/pandoc-2.17.1.1-linux-amd64.tar.gz"
+            ;;
+        linux-arm64)
+            printf "%s" "2.17.0.1/pandoc-2.17.1.1-linux-arm64.tar.gz"
+            ;;
+        *)
+            printf "System Not Supported: %s\n" "$sys" >&2
+            return 1
+    esac
+}
+
+___x_cmd_pandoc_bin_download_url_host(){
+    if "$___X_CMD_WHICHNET"; then
+        printf "%s" "https://github.com/jgm/pandoc/releases/download/"
+    else
+        printf "%s" "https://github.com.cnpmjs.org/jgm/pandoc/releases/download/"
+    fi
+}
+
+___x_cmd_pandoc_bin_download(){
+    local p
+    if ! p="$(___x_cmd_pandoc_bin_download_url_path)"; then
+        return 1
+    fi
+    local cache
+    cache="$(___x_cmd_pandoc_bin_default)"
+    p="$(___x_cmd_pandoc_bin_download_url_host)${p}"
+    if ! ___x_cmd_httpget "$p" "$cache"; then
+        printf "Download failed: %s\n" "$p" >&2
+        return 1
+    fi
+    printf "%s\n" "$cache"
+}
+
+___x_cmd_pandoc_bin_which(){
+    local bin
+    bin="$(___x_cmd_pandoc_bin_default)"
+    [ -f "$bin" ] || \
+        bin="$(command -v pandoc 2>/dev/null)" || \
+        bin="$(___x_cmd_pandoc_bin_download)" || return 1
+    printf "%s\n" bin
+}
+
+___x_cmd_pandoc_bin_init(){
+    local bin
+    if ! bin="$(___x_cmd_pandoc_which)"; then
+        printf "%s\n" "Cannot find local pandoc or install pandoc." >&2
+        return 1
+    fi
+
+    local funcname="${1:?Provide function name}"
+
+    eval "
+    $funcname(){
+        $bin \"\$@\"
+    }
+    "
+}
+
+___x_cmd_pandoc(){
+    ___x_cmd_pandoc_bin_init ___x_cmd_pandoc && ___x_cmd_pandoc "$@"
 }
 
 xrc setmain ___x_cmd_pandoc
