...

diff --git a/latest b/latest
--- a/latest
+++ b/latest
@@ -4,18 +4,25 @@
 # license:      GPLv3
 
 ___x_cmd_pandoc(){
-    ___x_cmd_staticbin_init ___x_cmd_pandoc_which ___x_cmd_pandoc && ___x_cmd_pandoc "$@"
+    ___x_cmd_staticbin_init \
+        ___x_cmd_pandoc \
+        "$___X_CMD_ROOT/.bin/pandoc" \
+        pandoc \
+        ___x_cmd_pandoc_bin_download_url_host \
+        ___x_cmd_pandoc_bin_download_url_path \
+        && ___x_cmd_pandoc "$@"
 }
 
-# Section: init
+# Section: staticbin
 ___x_cmd_staticbin_init(){
     local funcname="${1:?Provide function name}"
     local cachebin="${2:?Provide local bin name}"
-    local sysbin="${2:?Provide local bin name}"
-    local downloader="${3:?Provide exe name}"
+    local sysbin="${3:?Provide local bin name}"
+    local f_host="${4:?version fun}"
+    local f_path="${5:?version fun}"
 
     local bin
-    if ! bin="$(___x_cmd_staticbin_which "$cachebin" "$sysbin" "$downloader")"; then
+    if ! bin="$(___x_cmd_staticbin_which "$cachebin" "$sysbin" "$f_host" "$f_path" )"; then
         printf "%s\n" "Cannot find executable file." >&2
         return 1
     fi
@@ -30,27 +37,39 @@ ___x_cmd_staticbin_init(){
 ___x_cmd_staticbin_which(){
     local cachebin="${1:?Provide default cache bin}"
     local sysbin="${2:?Sysbin name}"
-    local downloader="${3:?Downloader}"
+    local f_host="${3:?version fun}"
+    local f_path="${4:?version fun}"
 
     [ -f "$cachebin" ] && printf "%s\n" "$cachebin" && return
     command -v "$sysbin" 2>/dev/null || return
-    "$downloader" "$cachebin" && printf "%s\n" "$cachebin" && return
+    ___x_cmd_staticbin_download "$cachebin" "$f_host" "$f_path" && printf "%s\n" "$cachebin" && return
 }
 
-# 1. Version provider
-# 2. Platform Provider
+# 1. cachebin
+# 2. SubPath Provider
 # 3. Root Provider
-___x_cmd_pandoc_bin_download(){
+___x_cmd_staticbin_download(){
     local cache="${1:?Provide path}"
+    local f_host="${2:?version fun}"
+    local f_path="${3:?version fun}"
+
     local p
-    if ! p="$(___x_cmd_pandoc_bin_download_url_path)"; then
+    if ! p="$($f_path)"; then
         return 1
     fi
-    p="$(___x_cmd_pandoc_bin_download_url_host)${p}"
-    if ! ___x_cmd_httpget "$p" "$cache"; then
-        printf "Download failed: %s\n" "$p" >&2
-        return 1
-    fi
+
+    local IFS="
+"
+
+    local line
+    $f_host | while read -r line; do
+        url="${line%/}/${p}"
+        if ! ___x_cmd_httpget "$url" "$cache"; then
+            printf "Download failed: %s\n" "$url" >&2
+            return 1
+        fi
+    done
+
 }
 # EndSection
 
